name: fixy_home_service
description: "A DreamFlow project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  url_launcher: ^6.0.0
  intl: 0.20.2
  confetti: 0.8.0
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  http: ^1.3.0
  qr_flutter: ^4.1.0
  supabase_flutter: '>=1.10.0'
  file_picker: '>=8.1.2'
  uuid: ^4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: ^6.2.1
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  provider: 6.1.2
  geolocator: 13.0.4
  geocoding: ^4.0.0
  flutter_svg: ^2.0.0
  table_calendar: ^3.0.0
  google_sign_in: '>=6.2.1'
  video_player: '>=2.9.2'
  chewie: ^1.7.5
  lottie: ^3.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Lufga
      fonts:
        - asset: assets/fonts/LufgaThin.ttf
          weight: 100
        - asset: assets/fonts/LufgaExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LufgaLight.ttf
          weight: 300
        - asset: assets/fonts/LufgaRegular.ttf
          weight: 400
        - asset: assets/fonts/LufgaMedium.ttf
          weight: 500
        - asset: assets/fonts/LufgaSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LufgaBold.ttf
          weight: 700
        - asset: assets/fonts/LufgaExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LufgaBlack.ttf
          weight: 900
        - asset: assets/fonts/LufgaThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/LufgaExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/LufgaLightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/LufgaItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/LufgaMediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/LufgaSemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/LufgaBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/LufgaExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/LufgaBlackItalic.ttf
          style: italic
          weight: 900
  assets:
    - assets/images/
    - assets/fonts/
    - assets/documents/